version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.08
    resource_class: xlarge
    steps:
      - run:
          name: Check ENV
          command: |
            echo "CPU threads: $(nproc --all)"
            free -g
            grep 'model name' /proc/cpuinfo | uniq
      - setup_remote_docker:
          version: 20.10.24
          docker_layer_caching: true
          
      - checkout
      - run:
          name: ls
          command: ls -lh
      - run:
          name: Build script
          command: |
            ls -lh
            echo "DBG: PWD is $(pwd)"
            mkdir /tmp/artifacts
            docker pull ubuntu:23.04
            docker run \
              -t \
              -v /home/circleci/project:/repo \
              ubuntu:23.04 \
              /bin/bash -c 'apt-get update && \
              apt-get install -y lsb-release git && \
              mkdir /tmp/artifacts && \
              git clone https://github.com/mahboobkarimian/T2-Ubuntu-Kernel.git && \
              cd T2-Ubuntu-Kernel && ls -lh && \
              ./build.sh && mkdir /repo/debs && \
              cp -r /tmp/artifacts/* /repo/debs'
            cp -r "$(pwd)"/debs/* /tmp/artifacts

            echo Built finished
            cd /tmp/artifacts
            ls -l
            dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
            ls -l

      - store_artifacts:
          path: /tmp/artifacts/*
