version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:23.04
    steps:
      - run:
          name: Check ENV
          command: |
            echo "CPU threads: $(nproc --all)"
            free -g
            grep 'model name' /proc/cpuinfo | uniq
      - checkout
      - run:
          name: ls
          command: ls -lh
      - run:
          name: Build script
          command: |
            ls -lh
            echo "DBG: PWD is $(pwd)"
            mkdir /tmp/artifacts
            ./build.sh
            echo "Built finished"
            cd /tmp/artifacts
            ls -l
            dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
            ls -l

      - store_artifacts:
          path: /tmp/artifacts/*
