---
name: Build Kernel Package

# yamllint disable-line rule:truthy
on:
  push:
    paths-ignore:
      - 'apt-repo/*.txt'
  pull_request:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v4.3.0
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
          sudo apt-get install shellcheck bash
      - name: 'Analysing the code'
        run: |
          yamllint -c ${{ github.workspace }}/.github/workflows/.ymllint .
          shellcheck ./*.sh
  Build-Focal:
    needs: [Lint]
    runs-on: ubuntu-20.04
    steps:

      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Build script
        id: build
        run: |
          mkdir /tmp/artifacts
          VERSION=$(grep ^KERNEL_VERSION build.sh | head -n1| cut -d = -f2)
          REL=$(grep "PKGREL=\d*" build.sh | cut -d = -f2)
          #REL=$( git tag |grep -F $VERSION|sort -r|head -n1|tr -d v)
          echo Building $VERSION-$REL
          echo "tag=${VERSION}-${REL}" >> $GITHUB_OUTPUT
          sudo ./build.sh

          cd /tmp/artifacts
          #rm /tmp/artifacts/*dbg*
          ls -l
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -l
      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2-${{ steps.build.outputs.tag }}-focal
          path: /tmp/artifacts/*

      - name: Release
        if: github.ref == 'refs/heads/LTS'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/sha256*
            /tmp/artifacts/*.deb
            /tmp/artifacts/kernel_config*
          tag_name: v${{ steps.build.outputs.tag }}
          body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Build-Jammy:
    needs: [Lint]
    runs-on: ubuntu-22.04
    steps:

      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Build script
        id: build
        run: |
          mkdir /tmp/artifacts
          VERSION=$(grep ^KERNEL_VERSION build.sh | head -n1| cut -d = -f2)
          REL=$(grep "PKGREL=\d*" build.sh | cut -d = -f2)
          #REL=$( git tag |grep -F $VERSION|sort -r|head -n1|tr -d v)
          echo Building $VERSION-$REL
          echo "tag=${VERSION}-${REL}" >> $GITHUB_OUTPUT
          sudo ./build.sh

          cd /tmp/artifacts
          #rm /tmp/artifacts/*dbg*
          ls -l
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -l

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2-${{ steps.build.outputs.tag }}-jammy
          path: /tmp/artifacts/*

      - name: Release
        if: github.ref == 'refs/heads/LTS'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/sha256*
            /tmp/artifacts/*.deb
            /tmp/artifacts/kernel_config*
          tag_name: v${{ steps.build.outputs.tag }}
          body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Build-Lunar:
    needs: [Lint]
    runs-on: ubuntu-22.04
    steps:

      - name: Free up disk space for the CI
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: 'Checkout Repo'
        uses: actions/checkout@v3

      - name: Build script
        id: build
        run: |
          mkdir /tmp/artifacts
          VERSION=$(grep ^KERNEL_VERSION build.sh | head -n1| cut -d = -f2)
          REL=$(grep "PKGREL=\d*" build.sh | cut -d = -f2)
          #REL=$( git tag |grep -F $VERSION|sort -r|head -n1|tr -d v)
          echo Building $VERSION-$REL
          echo "tag=${VERSION}-${REL}" >> $GITHUB_OUTPUT

          DOCKER_IMAGE=ubuntu:23.04
          docker pull ${DOCKER_IMAGE}
          docker run \
          -t \
          -v "$(pwd)":/repo \
          ${DOCKER_IMAGE} \
          /bin/bash -c 'cd /repo && \
          apt-get update && \
          apt-get install -y lsb-release python3 && \
          mkdir /tmp/artifacts && \
          ./build.sh && mkdir /repo/debs && \
          cp -r /tmp/artifacts/* /repo/debs'
          cp -r "$(pwd)"/debs/* /tmp/artifacts

          cd /tmp/artifacts
          #rm /tmp/artifacts/*dbg*
          ls -l
          dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          ls -l

      - name: Upload package artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-T2-${{ steps.build.outputs.tag }}-lunar
          path: /tmp/artifacts/*

      - name: Release
        if: github.ref == 'refs/heads/LTS'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/sha256*
            /tmp/artifacts/*.deb
            /tmp/artifacts/kernel_config*
          tag_name: v${{ steps.build.outputs.tag }}
          body_path: ${{ github.workspace }}/.github/workflows/instructions.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
